export type TreeNode<T extends {} = {}> = T & {
  groupBottomY: number;
  groupLeftX: number;
  groupMaxHeight: number;
  groupMaxWidth: number;
  groupRightX: number;
  groupTopY: number;
  height: number;
  isAncestor?: boolean;
  isDescendant?: boolean;
  isNext?: boolean;
  isNextAfter?: boolean;
  isNextBefore?: boolean;
  isRoot?: boolean;
  isSource?: boolean;
  isTarget?: boolean;
  marginBottom: number;
  marginRight: number;
  width: number;
  x: number;
  y: number;
};
